config/routes.rb
Lutgendorf::Application.routes.draw do
  devise_for :participants
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  get 'navigator/next_content', to: 'navigator#show_next_content', as: 'navigator_next_content'
  get 'navigator/contexts/:context_name', to: 'navigator#show_context', as: 'navigator_context'
  get 'navigator/modules/:module_id(/providers/:provider_id/:content_position)', to: 'navigator#show_location', as: 'navigator_location'
  resource :participant_data, only: [:create, :update]
  resource :flow, only: :show

  root to: 'navigator#show_context'  

end

app/models/daily_relaxation_session.rb
class DailyRelaxationSession < ActiveRecord::Base
  belongs_to :participant
  has_many :listenings
end

app/views/daily_relaxation_sessions/daily_relaxation_post_form.html.erb
<h1>Using the following scale, rate your stress level right now after you have practiced your relaxation session</h1>

<%= form_for daily_relaxation_session, url: update_path, :html => {:method => :put, :role => "form"} do |f| %>
 <div class="form-group">
  <div class="row form-labels">
    <div class="col-md-4"><span class="form-label-text">No Stress</span></div>
    <div class="col-md-4"><span class="form-label-text">Moderately Stressed</span></div>
    <div class="col-md-4"><span class="form-label-text">Extremely Stressed</span></div>
  </div>
      <%= f.hidden_field :id, :value => daily_relaxation_session.id %>

    <%= f.range_field :post_stress, :in => 0..10, :step => '.1', :id => "range" %><Br/>
    <%= f.submit "Submit", :class => "form-control btn btn-primary btn-lg" %>
  </div>
<%end%>
<script>
 $(document).ready(function() {
    customSlider($('#range'));
  });
</script>

app/views/daily_relaxation_sessions/daily_relaxation_pre_form.html.erb
<h1>Using the following scale, rate your stress level right now before you practice your relaxation session</h1>

<%= form_for DailyRelaxationSession.new, url: create_path, :html => {:role => "form"} do |f| %>

  <div class="form-group">
    <div class="row form-labels">
      <div class="col-md-4"><span class="form-label-text">No Stress</span></div>
      <div class="col-md-4"><span class="form-label-text">Moderately Stressed</span></div>
      <div class="col-md-4"><span class="form-label-text">Extremely Stressed</span></div>
    </div>
    <%= f.range_field :pre_stress, :in => 0..10, :step => '.1', :id => "range" %>
    <%= f.submit "Continue", :class => "form-control btn btn-primary btn-lg" %>
  </div>
<%end%>
<script>
 $(document).ready(function() {
    customSlider($('#range'));
  });
</script>

app/views/daily_relaxation_sessions/relaxation_audio_index.html.erb
<h1>Instructions</h1>

<%= form_for Listening.new, url: create_path, :html => {:method => :post, :role => "form"} do |f| %>
  <div class="checkbox">
    <%= f.label :self_guided do %>
      <%= f.check_box :self_guided %>
      Check if you prefer to guide this relaxation session without audio.
    <% end %>
    <br>
    <%= f.hidden_field :daily_relaxation_session_id , value: current_relaxation_session.id%>
    <%= f.submit 'Complete self-guided medtitation', :class => 'btn btn-primary'  %>
  </div>
<% end %>

<% audio_files.each do |file| %>
  <div class="row">
    <div class="col-md-4">
      <div class='main-nav-button audio'><h2><%=file.title%></h2>
        <% if file.is_released?(current_participant) %>
          <audio src="<%=file.sound_file%>" data-id="<%=file.id%>" controls type="audio/mpeg" style="position:relative;bottom:-15px;">
            Your browser does not support the audio element.
          </audio>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<script>
  $(document).ready(function() {

    $('audio').on("click", function(){
      $.ajax({
        url: "<%= create_path %>.js",
        type: "POST",
        data: {"listening":{'relaxation_audio_id': $(this).data("id"), 'daily_relaxation_session_id': "<%=current_relaxation_session.id%>"}}
      });
    });
    $('.btn-primary').text('Exercise Complete');
  });
</script>