config/routes.rb
Lutgendorf::Application.routes.draw do
  devise_for :participants
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  get 'navigator/next_content', to: 'navigator#show_next_content', as: 'navigator_next_content'
  get 'navigator/contexts/:context_name', to: 'navigator#show_context', as: 'navigator_context'
  get 'navigator/modules/:module_id(/providers/:provider_id/:content_position)', to: 'navigator#show_location', as: 'navigator_location'
  resource :participant_data, only: [:create, :update]
  resource :flow, only: :show

  root to: 'navigator#show_context'  

end

app/views/shared/_alerts.html.erb
<% if alert %>
  <%= icon('flag', alert, class: 'text-danger fa-spin') %>
<% elsif notice %>
  <%= icon('flag', notice, class: 'text-success') %>
<% end %>

app/views/shared/_authentication.html.erb
<div id="auth_nav">
	<% if current_participant %>
	  <%= link_to "<i class='icon-signout'></i> Sign Out".html_safe, destroy_participant_session_path, method: :delete %>
	<% end %>
</div>

app/views/shared/_footer.html.erb
<footer>
	&copy; <%= Date.today.year %> Lutgendorf | 
	<%= link_to "Susan Lutgendorf", "" %> |  
	<%= link_to "Privacy Policy", "/privacy" %>
</footer>

app/views/shared/_home.html.erb
<div id="home_nav">
<%= link_to "<i class='icon-home'></i> Home".html_safe, "/"%>
</div>

app/views/shared/_welcome_message.html.erb
<div style="text-align:center;color:darkslateblue;" id="welcome-message">
  <h3>Welcome, <%=current_participant.first_name rescue current_participant.email%></h3>
</div>