config/routes.rb
Lutgendorf::Application.routes.draw do
  devise_for :participants
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  get 'navigator/next_content', to: 'navigator#show_next_content', as: 'navigator_next_content'
  get 'navigator/contexts/:context_name', to: 'navigator#show_context', as: 'navigator_context'
  get 'navigator/modules/:module_id(/providers/:provider_id/:content_position)', to: 'navigator#show_location', as: 'navigator_location'
  resource :participant_data, only: [:create, :update]
  resource :flow, only: :show

  root to: 'navigator#show_context'  

end

app/models/content_providers/home.rb
class ContentProviders::Home < ContentProvider

  def render_current(options)
    content_modules = ContentModule
      .where(context: options.app_context)
      .where.not(id: content_module_id)

    options.view_context.render(
      template: 'home/index',
      locals: { content_modules: content_modules }
    )
  end

  def exists?(position)
    false
  end

  def show_nav_link?
    false
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_participant!

  def index
  end
end

app/views/home/index.html.erb
<div class="row main-nav">
  <div class="col-md-12">
    <div class="col-md-12">
      <img src="/images/logo.png" style="width:120px; height:116px; float:left;margin-top:10px; margin-bottom:10px;"><h1 id="logo-text" style="color:darkslateblue;">LivingWell</h1>
    </div>
    <div class="row">
      <div class="col-md-12">
        <% AppSection.all.each do |s| %>
          <% if s.label != "Qualtrics" %>
            <%= link_to("<div class='main-nav-button home' id='#{s.slug}'><span class='tool-text'>#{ s.label }</span></div>".html_safe, navigator_context_path(context_name: s.slug)) %>
            <%end%>
            
            <% if s.label == "Qualtrics" && s.qualtrics_visible?(current_participant) %>
              <%= link_to("<div class='main-nav-button home'><span class='tool-text'>#{ s.label }</span></div>".html_safe, s.qualtrics_link(current_participant), :class=> 'qualtrics-link', :target => 'blank') %>
            </div>
            <% end%>
        <% end %>
    </div>
  </div>
</div>